#!/usr/bin/env bash

[[ -n $1 ]] || exit 1

echo "Checking"

re="([a-zA-Z]+):.*"
if [[ $1 =~ $re ]]; then 
	echo "match"
	mimetype=x-scheme-handler/${BASH_REMATCH[1]}
	nw $(dirname $(realpath $0)) $1 $mimetype
else
	mimetype=`file --mime-type -b -E "$1"` || exit 1
	echo doing "nw $(dirname $(realpath $0)) $(realpath $1) $mimetype" 
	nw $(dirname $(realpath $0)) $(realpath $1) $mimetype	
fi
