/* _nolicense _*/
package mimetypes

/**
 * Theese are the uri schemes from https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml, marked 'Permanent'.
 * I assume it is in the public domain, copyright wise.
 */
var schemeHandlers = map[string]string{
	"x-scheme-handler/aaa":             "Diameter Protocol",
	"x-scheme-handler/aaas":            "Diameter Protocol with Secure Transport",
	"x-scheme-handler/about":           "about",
	"x-scheme-handler/acap":            "application configuration access protocol",
	"x-scheme-handler/acct":            "acct",
	"x-scheme-handler/cap":             "Calendar Access Protocol",
	"x-scheme-handler/cid":             "content identifier",
	"x-scheme-handler/coap":            "coap",
	"x-scheme-handler/coap+tcp":        "coap+tcp [1]",
	"x-scheme-handler/coap+ws":         "coap+ws [1]",
	"x-scheme-handler/coaps":           "coaps",
	"x-scheme-handler/coaps+tcp":       "coaps+tcp [1]",
	"x-scheme-handler/coaps+ws":        "coaps+ws [1]",
	"x-scheme-handler/crid":            "TV-Anytime Content Reference Identifier",
	"x-scheme-handler/data":            "data",
	"x-scheme-handler/dav":             "dav",
	"x-scheme-handler/dict":            "dictionary service protocol",
	"x-scheme-handler/dns":             "Domain Name System",
	"x-scheme-handler/example":         "example",
	"x-scheme-handler/file":            "Host-specific file names",
	"x-scheme-handler/ftp":             "File Transfer Protocol",
	"x-scheme-handler/geo":             "Geographic Locations",
	"x-scheme-handler/go":              "go",
	"x-scheme-handler/gopher":          "The Gopher Protocol",
	"x-scheme-handler/h323":            "H.323",
	"x-scheme-handler/http":            "Hypertext Transfer Protocol",
	"x-scheme-handler/https":           "Hypertext Transfer Protocol Secure",
	"x-scheme-handler/iax":             "Inter-Asterisk eXchange Version 2",
	"x-scheme-handler/icap":            "Internet Content Adaptation Protocol",
	"x-scheme-handler/im":              "Instant Messaging",
	"x-scheme-handler/imap":            "internet message access protocol",
	"x-scheme-handler/info":            "Information Assets",
	"x-scheme-handler/ipp":             "Internet Printing Protocol",
	"x-scheme-handler/ipps":            "Internet Printing Protocol over HTTPS",
	"x-scheme-handler/iris":            "Internet Registry Information Service",
	"x-scheme-handler/iris.beep":       "iris.beep",
	"x-scheme-handler/iris.lwz":        "iris.lwz",
	"x-scheme-handler/iris.xpc":        "iris.xpc",
	"x-scheme-handler/iris.xpcs":       "iris.xpcs",
	"x-scheme-handler/jabber":          "jabber",
	"x-scheme-handler/ldap":            "Lightweight Directory Access Protocol",
	"x-scheme-handler/leaptofrogans":   "leaptofrogans",
	"x-scheme-handler/mailto":          "Electronic mail address",
	"x-scheme-handler/mid":             "message identifier",
	"x-scheme-handler/msrp":            "Message Session Relay Protocol",
	"x-scheme-handler/msrps":           "Message Session Relay Protocol Secure",
	"x-scheme-handler/mtqp":            "Message Tracking Query Protocol",
	"x-scheme-handler/mupdate":         "Mailbox Update (MUPDATE) Protocol",
	"x-scheme-handler/news":            "USENET news",
	"x-scheme-handler/nfs":             "network file system protocol",
	"x-scheme-handler/ni":              "ni",
	"x-scheme-handler/nih":             "nih",
	"x-scheme-handler/nntp":            "USENET news using NNTP access",
	"x-scheme-handler/opaquelocktoken": "opaquelocktokent",
	"x-scheme-handler/pkcs11":          "PKCS#11",
	"x-scheme-handler/pop":             "Post Office Protocol v3",
	"x-scheme-handler/pres":            "Presence",
	"x-scheme-handler/reload":          "reload",
	"x-scheme-handler/rtsp":            "Real-Time Streaming Protocol (RTSP)",
	"x-scheme-handler/rtsps":           "Real-Time Streaming Protocol (RTSP) over TLS",
	"x-scheme-handler/rtspu":           "Real-Time Streaming Protocol (RTSP) over unreliable datagram transport",
	"x-scheme-handler/service":         "service location",
	"x-scheme-handler/session":         "session",
	"x-scheme-handler/shttp":           "Secure Hypertext Transfer Protocol",
	"x-scheme-handler/sieve":           "ManageSieve Protocol",
	"x-scheme-handler/sip":             "session initiation protocol",
	"x-scheme-handler/sips":            "secure session initiation protocol",
	"x-scheme-handler/sms":             "Short Message Service",
	"x-scheme-handler/snmp":            "Simple Network Management Protocol",
	"x-scheme-handler/soap.beep":       "soap.beep",
	"x-scheme-handler/soap.beeps":      "soap.beeps",
	"x-scheme-handler/stun":            "stun",
	"x-scheme-handler/stuns":           "stuns",
	"x-scheme-handler/tag":             "tag",
	"x-scheme-handler/tel":             "telephone",
	"x-scheme-handler/telnet":          "Reference to interactive sessions",
	"x-scheme-handler/tftp":            "Trivial File Transfer Protocol",
	"x-scheme-handler/thismessage":     "multipart/related relative reference resolution",
	"x-scheme-handler/tip":             "Transaction Internet Protocol",
	"x-scheme-handler/tn3270":          "Interactive 3270 emulation sessions",
	"x-scheme-handler/turn":            "turn",
	"x-scheme-handler/turns":           "turns",
	"x-scheme-handler/tv":              "TV Broadcasts",
	"x-scheme-handler/urn":             "Uniform Resource Names",
	"x-scheme-handler/vemmi":           "versatile multimedia interface",
	"x-scheme-handler/vnc":             "Remote Framebuffer Protocol",
	"x-scheme-handler/ws":              "WebSocket connections",
	"x-scheme-handler/wss":             "Encrypted WebSocket connections",
	"x-scheme-handler/xcon":            "xcon",
	"x-scheme-handler/xcon-userid":     "xcon-userid",
	"x-scheme-handler/xmlrpc.beep":     "xmlrpc.beep",
	"x-scheme-handler/xmlrpc.beeps":    "xmlrpc.beeps",
	"x-scheme-handler/xmpp":            "Extensible Messaging and Presence Protocol",
	"x-scheme-handler/z39.50r":         "Z39.50 Retrieval",
	"x-scheme-handler/z39.50s":         "Z39.50 Session",
}
