#!/usr/bin/env bash

set -e
[[ -n $1 ]] || exit 1

echo "Checking"

re="([a-zA-Z]+):.*"
if [[ $1 =~ $re ]]; then 
	echo "match"
	mimetype=x-scheme-handler/${BASH_REMATCH[1]}
	nw $(dirname $(realpath $0)) $1 $mimetype
else
	refudeDir=$(dirname $(realpath $0))
	path=`realpath "$1"`
	mimetype=`file --mime-type -b -E "$1"` 
	nw $refudeDir "$path" $mimetype
fi
